package com.codeathon.tables;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Set;

@DynamoDBTable(tableName = "ConfigParams")
public class ConfigParams {

    private String id;
    private String productName;
    private String messageType;
    private Set<String> paths;
    private Set<String> searchKeywords;
    private String isDeafult;
    private String partnerId;
    private String contentType;
    private String payload;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBAttribute
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }
    @DynamoDBAttribute
    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }
    @DynamoDBAttribute
    public Set<String> getPaths() {
        return paths;
    }

    public void setPaths(Set<String> paths) {
        this.paths = paths;
    }
    @DynamoDBAttribute
    public Set<String> getSearchKeywords() {
        return searchKeywords;
    }

    public void setSearchKeywords(Set<String> searchKeywords) {
        this.searchKeywords = searchKeywords;
    }
    @DynamoDBAttribute
    public String getIsDeafult() {
        return isDeafult;
    }

    public void setIsDeafult(String isDeafult) {
        this.isDeafult = isDeafult;
    }
    @DynamoDBAttribute
    public String getPartnerId() {
        return partnerId;
    }

    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }
    @DynamoDBAttribute
    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }
    @DynamoDBAttribute
    public String getPayload() {
        return payload;
    }

    public void setPayload(String payload) {
        this.payload = payload;
    }

    public ConfigParams() {
    }


}
