package com.codeathon.tables;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Set;

@DynamoDBTable(tableName = "ProductType")
public class ProductType {
    private String id;
    private String name;
    private Set<String> messageTypes;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public Set<String> getMessageTypes() {
        return messageTypes;
    }

    public void setMessageTypes(Set<String> messageTypes) {
        this.messageTypes = messageTypes;
    }

    public ProductType() {
    }

    public ProductType(String name, Set<String> messageTypes) {
        this.name = name;
        this.messageTypes = messageTypes;
    }
}
