AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 Instance for MongoDB
Parameters:
  VpcId:
    Description: "vpcid to be deployed to"
    Type: String
  ImageId:
    Description: "ImageId to be deployed to"
    Type: String

Resources:
  MongoDBEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: codeathon
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MongoDBSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: !Sub |
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo docker run -d -p 27017:27017 mongo:latest

  MongoDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-3fc63654
      GroupDescription: Allow traffic for MongoDB
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 27017
          IpProtocol: tcp
          ToPort: 27017
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Type: String
    Value: !Ref MongoDBEC2Instance
  AZ:
    Value: !GetAtt [ MongoDBEC2Instance, AvailabilityZone]
  val2:
    Value: !GetAtt [ MongoDBEC2Instance, PublicDnsName]
  val3:
    Value: !GetAtt [ MongoDBEC2Instance, PublicIp]