AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance for Rest Service
Parameters:
  VpcId:
    Description: "vpcid to be deployed to"
    Type: String
  ImageId:
    Description: "ImageId to be deployed to"
    Type: String

Resources:
  EC2InstanceForRestService:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: codeathon
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo docker run -d -p 8090:8090 -e mongodbhostname=ec2-18-217-62-164.us-east-2.compute.amazonaws.com okuswaha/nextgen-simtool-service:1.1

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable HTTP access via user defined port
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Type: String
    Value: !Ref EC2InstanceForRestService
  AZ:
    Value: !GetAtt [ EC2InstanceForRestService, AvailabilityZone]
  val2:
    Value: !GetAtt [ EC2InstanceForRestService, PublicDnsName]
  val3:
    Value: !GetAtt [ EC2InstanceForRestService, PublicIp]