AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance for Rest Service
Resources:
  EC2InstanceForRestService:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dacb0c129b49f529
      KeyName: codeathon
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo docker run -d -p 8090:8090 -e mongodbhostname=ec2-18-217-62-164.us-east-2.compute.amazonaws.com okuswaha/nextgen-simtool-service:1.1

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable HTTP access via user defined port\
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80