AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance for Rest Service
Resources:
  EC2InstanceForRestService:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: codeathon
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable HTTP access via user defined port\
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80