AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance for Simtool UI
Resources:
  UIEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]]
      InstanceType: 't2.micro'