AWSTemplateFormatVersion: "2010-09-09"
Description: "Table to store product types"
Resources:
  ProductTypeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      TableName: "ProductType"
      KeySchema:
        -  AttributeName: "id"
           KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ConfigParamsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      TableName: "ConfigParams"
      KeySchema:
        -  AttributeName: "id"
           KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  SimulationDataTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      TableName: "SimulationData"
      KeySchema:
        -  AttributeName: "id"
           KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

Outputs:
  ProductTypeTableId:
    Value: !Ref ProductTypeTable
  ConfigParamsTableTableId:
    Value: !Ref ConfigParamsTable
  SimulationDataTableId:
    Value: !Ref SimulationDataTable

